name: TestMachine Scan
description: Test and attack your solidity smart contracts with AI.
#
inputs:
  tm_repository_id:
    description: Repository Id in TestMachine
    required: true
  tm_source:
    description: The file to be sent to TestMachine
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.tm_repository_id }}
    - ${{ inputs.tm_source }}
#
branding:
  icon: check
  color: green
